### ISSUE TITLE
ERROR: A failure occurred in prepare().

### ISSUE THREAD

**Issue by tuxarch** [Frogging-Family/nvidia-all#143]
Hunk #1 FAILED at 3585.
1 out of 1 hunk FAILED -- saving rejects to file conftest.sh.rej
patching file nvidia-drm/nvidia-drm-drv.c
Hunk #1 succeeded at 680 (offset 21 lines).

Arch linux
Linux arch 6.1.4-arch1-1

9.Custom version (396.xx series or higher)
1.Stable or regular beta
396.54.09
1.dkms

**Comment by Tk-Glitch** [comment]
> 1.Stable or regular beta

396.54.09 is a vulkan dev driver, so that's wrong :frog:

Anyway, 396 series will only work up to kernel 5.3 (with our patches). 5.1 being the recommended newest kernel to use with those.

I'm pretty sure 520 or 525 series is required for kernel 6.1 on non-legacy GPUs (470.161.03 for Kepler, and 390.157 for Fermi, which is not supported by nvidia-all tool)

See https://github.com/Frogging-Family/nvidia-all/blob/9318fb0b3aa8ce332215c627721e7926eaccdb64/PKGBUILD#L79

Anyway I have corrected the checks so the patch attempt won't happen on unsupported kernel revisions anymore. The driver modules will fail to build against incompatible kernels though, as expected.
