### ISSUE TITLE
Cannot build 535.43.02

### ISSUE THREAD

**Issue by BlueGoliath** [Frogging-Family/nvidia-all#169]
Fails with: `cannot stat 'libnvidia-compiler.so.535.43.02': No such file or directory`.

**Comment by gardotd426** [comment]
...isn't it 535.43.03 anyway?

**Comment by gardotd426** [comment]
Oh wait, that's 530. Nevermind I'm stupid

**Comment by gardotd426** [comment]
@BlueGoliath `libnvidia-compiler.so` has been removed:

>- Removed libnvidia-compiler.so.VERSION from the driver package. This functionality is now provided by other driver libraries.

You could probably just comment out the lines from the PKGBUILD, or change them to `if -e` statements the same way the `libnvidia-compiler-next.so.$pkgver` lines are done.

**Comment by gardotd426** [comment]
What monitoring utility do you use?

**Comment by gardotd426** [comment]
I added a comment seconding what you said. If they don't respond by like
tomorrow I would send an email, I've always had better luck going that
route (or doing both, it seems I usually get a rather quick response doing
that.

**Comment by notpentadactyl** [comment]
Saancreed also mentioned that there is a new file `nvoptix.bin` that needs to be packaged.

**Comment by gardotd426** [comment]
Yeah, I knew that but forgot to mention it, but unfortunately I don'tt
believe it will fix BlueGoliath's problem. Hopefully Nvidia doesn't take
forever to fix it. It'd be nice to know whether things like GWE still work,
I haven't installed the drivers yet.

**Comment by gardotd426** [comment]
>To clarify, it's only an issue if you use a function that takes in nvmlProcessInfo_t struct type. I've fixed it on my end and my app works again. Everything else works fine in NVML as it did before for now. Someone might want to maintain GWE again though.

I will say that I installed the drivers (including `nvoptix.bin` which goes in `/usr/share/nvidia/`) and tested GWE and it worked perfectly fine. I couldn't use those drivers though because they break CUDA completely. At least they break a lot of it. Blender completely fails to even run any GPU benchmarks and when trying to render a `.blend` file it crashes with weird errors, I downgraded back to the Vulkan beta driver and the issues are all gone. 530.41.03 worked fine too. 

@BlueGoliath can you try and run `blender-benchmark` and do a GPU bench and see if you get the same errors? I reported it on the NV forums but haven't had any responses yet.

**Comment by ryanmusante** [comment]
This is the driver mentioned here?
https://www.phoronix.com/news/NVIDIA-535.43.02-Linux-Driver

**Comment by gardotd426** [comment]
Yes.

**Comment by fidasx** [comment]
same here blender doesn't work when trying to render it crashes with error
```sh
munmap_chunk(): invalid pointer
```

other 3d utils like glmark or vkcube work fine

**Comment by gardotd426** [comment]
It's CUDA that seems to be the problem, GLMark and VKCube don't use any CUDA/Optix stuff.

**Comment by ryanmusante** [comment]
535.42.02 is a beta, unless you want to spend considerable amount of time on nvidia dev forums troubleshooting, I'd stick to a working ver. I ran into issues aplenty and rolled back.

**Comment by gardotd426** [comment]
@ryanmusante Yeah. We're aware it's a beta. We run these things for a reason, because betas need to be tested. Without people who are willing to test beta releases, betas have no reason to exist. If that's not you, then don't run it.

**Comment by ryanmusante** [comment]
@gardotd426 I should at least open one ticket with nvidia to let them know about my particular configuration and show them the logs. It's just that it becomes incredibly time consuming. I am willing to an extent.

**Comment by gardotd426** [comment]
It's not really that time consuming, at all. 

I opened a thread regarding the CUDA Blender bug, and an Nvidia employee had replied within 24 hours with an internal bug tracking number, and the same day they reported that they'd found what the issue was and what I could do in the meantime to workaround it. 

It's not always *that* easy, but if it's an actual bug, and you take ten minutes to adequately describe it and include an `nvidia-bug-report.log.gz` or whatever, then that's usually all you need to do.
