### ISSUE TITLE
Support for linux-cachyos-lto-headers

### ISSUE THREAD

**Issue by hunabku94** [Frogging-Family/nvidia-all#227]
Can you please add support for linux-cachyos-lto-headers to prevent the warning for this kernel ?

Thanks a lot.

**Comment by ShadowFlarer** [comment]
I use the Cachyos-eevdf kernel and the headers is also not present, but theres a workaround, open the file PKGBUILD with a text editor (i recomend gedit because it shows the line numbers), around the line n# 247~ you will find this:

if [ $(pacman -Qs linux-headers | head -c1 | wc -c) -eq 0 ] && [ $(pacman -Qs linux-zen-headers | head -c1 | wc -c) -eq 0 ] && [ $(pacman -Qs linux-hardened-headers | head -c1 | wc -c) -eq 0 ] && [ $(pacman -Qs linux-neptune-dri-headers | head -c1 | wc -c) -eq 0 ] && [ $(pacman -Qs linux-cachyos-headers | head -c1 | wc -c) -eq 0 ] && [ $(pacman -Qs linux-cachyos-bore-headers | head -c1 | wc -c) -eq 0 ];

Where is "linux-zen-headers" change to your kernel headers, in my case i use "linux-cachyos-eevdf-headers", save the file and just install like normal and you won´t have troubles.
