### ISSUE TITLE
Uninstall scripts?

### ISSUE THREAD

**Issue by tamimmahmudkhan** [Frogging-Family/nvidia-all#41]
May we have uninstall scripts to remove all the installed packages from the last install along with all the custom configs? I ask because I originally tried nvidia vulkan drivers and then decided to go back to regular and had no way of removing the drivers so I uninstalled everything with the name nvidia in it and reinstalled.

**Comment by Tk-Glitch** [comment]
If we had to make uninstall scripts for packages, what would be the point in using packages in the first place? :stuck_out_tongue: 

Just install your distro drivers packages and since they will conflict with ours you'll be prompted about replacing them. There's no leftover when the packages are uninstalled or replaced this way since they are not considered as an upgrade but as a full replacement.

https://github.com/Frogging-Family/nvidia-all/issues/8
